"""GlobalMessage and PersonalMessage

Revision ID: 35db3834ebbc
Revises: f08751635e9f
Create Date: 2023-06-09 07:49:34.652694

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "35db3834ebbc"
down_revision = "f08751635e9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "GlobalMessage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["User.id"], name=op.f("fk_GlobalMessage_sender_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_GlobalMessage")),
    )
    op.create_index(
        op.f("ix_GlobalMessage_timestamp"), "GlobalMessage", ["timestamp"], unique=False
    )
    op.create_table(
        "PersonalMessage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("receiver_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["receiver_id"], ["User.id"], name=op.f("fk_PersonalMessage_receiver_id_User")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["User.id"], name=op.f("fk_PersonalMessage_user_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_PersonalMessage")),
    )
    op.create_index(
        op.f("ix_PersonalMessage_timestamp"), "PersonalMessage", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_PersonalMessage_timestamp"), table_name="PersonalMessage")
    op.drop_table("PersonalMessage")
    op.drop_index(op.f("ix_GlobalMessage_timestamp"), table_name="GlobalMessage")
    op.drop_table("GlobalMessage")
    # ### end Alembic commands ###
