"""changing user token to its own table

Revision ID: 4396ffda9a9f
Revises: 4c1e2204080d
Create Date: 2023-08-16 11:01:27.550853

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "4396ffda9a9f"
down_revision = "4c1e2204080d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UserToken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_expiration", sa.Integer(), nullable=False),
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("refresh_token_expiration", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["User.id"], name=op.f("fk_UserToken_user_id_User")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_UserToken")),
    )
    op.create_index(op.f("ix_UserToken_access_token"), "UserToken", ["access_token"], unique=False)
    op.drop_index("ix_User_token", table_name="User")
    op.drop_column("User", "token_expiration")
    op.drop_column("User", "token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(
        "User", sa.Column("token_expiration", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_User_token", "User", ["token"], unique=False)
    op.drop_index(op.f("ix_UserToken_access_token"), table_name="UserToken")
    op.drop_table("UserToken")
    # ### end Alembic commands ###
