"""adding salt to user for password salting

Revision ID: 4c1e2204080d
Revises: 7761d1685d6b
Create Date: 2023-08-11 12:17:07.467909

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "4c1e2204080d"
down_revision = "7761d1685d6b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("salt", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "salt")
    # ### end Alembic commands ###
