"""Hexagon and Tile objects

Revision ID: 562a3ef81dcb
Revises: d59cee3a9f40
Create Date: 2023-06-08 13:49:30.577065

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "562a3ef81dcb"
down_revision = "d59cee3a9f40"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Hexagon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("q", sa.Integer(), nullable=False),
        sa.Column("r", sa.Integer(), nullable=False),
        sa.Column("tiles_detail", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Hexagon")),
    )
    op.create_index("hexagon_index", "Hexagon", ["q", "r"], unique=True)
    op.create_table(
        "Tile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hexagon_id", sa.Integer(), nullable=False),
        sa.Column("q", sa.Integer(), nullable=False),
        sa.Column("r", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_changed_by", sa.Integer(), nullable=True),
        sa.Column("last_changed_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hexagon_id"], ["Hexagon.id"], name=op.f("fk_Tile_hexagon_id_Hexagon")
        ),
        sa.ForeignKeyConstraint(
            ["last_changed_by"], ["User.id"], name=op.f("fk_Tile_last_changed_by_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Tile")),
    )
    op.create_index("tile_id_index", "Tile", ["id"], unique=True)
    op.create_index("tile_q_r_index", "Tile", ["q", "r"], unique=True)
    op.alter_column("Friend", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("Friend", "friend_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Friend", "friend_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("Friend", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_index("tile_q_r_index", table_name="Tile")
    op.drop_index("tile_id_index", table_name="Tile")
    op.drop_table("Tile")
    op.drop_index("hexagon_index", table_name="Hexagon")
    op.drop_table("Hexagon")
    # ### end Alembic commands ###
