"""adding the name on the friend object

Revision ID: 6599dfd90f5c
Revises: 35db3834ebbc
Create Date: 2023-06-12 18:59:24.104453

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "6599dfd90f5c"
down_revision = "35db3834ebbc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Friend", sa.Column("friend_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Friend", "friend_name")
    # ### end Alembic commands ###
