"""unread messages and remove obsolete stuff

Revision ID: 6cf202a83095
Revises: 4396ffda9a9f
Create Date: 2023-08-24 08:50:01.630756

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6cf202a83095"
down_revision = "4396ffda9a9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Friend", "last_time_activity")
    op.add_column("Guild", sa.Column("unread_messages", sa.Integer(), nullable=False))
    op.drop_column("User", "last_seen")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("last_seen", postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    op.drop_column("Guild", "unread_messages")
    op.add_column(
        "Friend",
        sa.Column(
            "last_time_activity", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
