"""adding guild messages

Revision ID: 7761d1685d6b
Revises: 1c588af12699
Create Date: 2023-08-08 08:41:22.425388

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "7761d1685d6b"
down_revision = "1c588af12699"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "GuildMessage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.Column("sender_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["User.id"], name=op.f("fk_GuildMessage_sender_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_GuildMessage")),
    )
    op.create_index(op.f("ix_GuildMessage_guild_id"), "GuildMessage", ["guild_id"], unique=False)
    op.create_index(op.f("ix_GuildMessage_timestamp"), "GuildMessage", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_GuildMessage_timestamp"), table_name="GuildMessage")
    op.drop_index(op.f("ix_GuildMessage_guild_id"), table_name="GuildMessage")
    op.drop_table("GuildMessage")
    # ### end Alembic commands ###
