"""adding guild

Revision ID: bcd80ee3066d
Revises: 6599dfd90f5c
Create Date: 2023-07-09 19:28:59.673934

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "bcd80ee3066d"
down_revision = "6599dfd90f5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
