"""adding guild


Revision ID: d383e841b5ff
Revises: 6599dfd90f5c
Create Date: 2023-07-09 19:58:50.879549

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "d383e841b5ff"
down_revision = "6599dfd90f5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Guild",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("guild_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("guild_crest", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("member_ids", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["User.id"], name=op.f("fk_Guild_user_id_User")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Guild")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Guild")
    # ### end Alembic commands ###
