apiVersion: v1
kind: Namespace
metadata:
  name: golden-age
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  namespace: golden-age
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      namespace: golden-age
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: age_of_gold:1.02
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: golden-age
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapi
  type: LoadBalancer


# kubectl get pods -n golden-age
# minikube service flask-service -n golden-age