version: '3.6'

services:
  age_of_api:
    container_name: age_of_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - default
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ${SHARED_DIR}:/app/static/uploads/
      - ./migrations:/app/migrations
    depends_on:
      - age_of_db
    links:
      - age_of_db

  age_of_db:
    container_name: age_of_db
    env_file: .env
    image: postgres:15.2
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    shm_size: 1g
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "max_parallel_workers=32"
      - "-c"
      - "max_parallel_workers_per_gather=8"
      - "-c"
      - "shared_buffers=4096MB"

  redis:
    image: redis:7.0.10
    ports:
      - 6379:6379
    command:
      - redis-server

  rabbit:
    image: "bitnami/rabbitmq:3.7"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbit
      - redis
    volumes:
      - "./:/app"
    command: "poetry run celery -A app.app.worker.celery_worker worker -l info -Q test-queue -c 1"
