"""adding a login origin to the user

Revision ID: 14e880e9a774
Revises: 38bb8bd661a8
Create Date: 2022-10-22 17:41:20.456938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e880e9a774'
down_revision = '38bb8bd661a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('origin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'origin')
    # ### end Alembic commands ###
