"""group functionality

Revision ID: 19c37ff8148b
Revises: 97bc978ba8ff
Create Date: 2026-01-15 22:01:30.855752

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19c37ff8148b"
down_revision: Union[str, Sequence[str], None] = "97bc978ba8ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Chat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("user_admin_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("group_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column(
            "group_description",
            sqlmodel.sql.sqltypes.AutoString(),  # type: ignore[attr-defined]
            nullable=False,
        ),
        sa.Column("group_colour", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("default_avatar", sa.Boolean(), nullable=False),
        sa.Column("current_message_id", sa.Integer(), nullable=False),
        sa.Column("last_message_read_id_chat", sa.Integer(), nullable=False),
        sa.Column("message_version", sa.Integer(), nullable=False),
        sa.Column("avatar_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Chat")),
    )
    op.create_table(
        "Group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("unread_messages", sa.Integer(), nullable=False),
        sa.Column("mute", sa.Boolean(), nullable=False),
        sa.Column("mute_timestamp", sa.DateTime(), nullable=True),
        sa.Column("last_message_read_id", sa.Integer(), nullable=False),
        sa.Column("group_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["Chat.id"], name=op.f("fk_Group_group_id_Chat")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["User.id"], name=op.f("fk_Group_user_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Group")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Group")
    op.drop_table("Chat")
    # ### end Alembic commands ###
