"""friend object has requested indicator

Revision ID: 24682eecd8d3
Revises: e1636aa46dff
Create Date: 2023-05-08 22:00:52.723771

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "24682eecd8d3"
down_revision = "e1636aa46dff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Friend", schema=None) as batch_op:
        batch_op.add_column(sa.Column("requested", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Friend", schema=None) as batch_op:
        batch_op.drop_column("requested")

    # ### end Alembic commands ###
