"""adding message objects

Revision ID: 2fd20c0c5358
Revises: 5eac8e246390
Create Date: 2023-04-27 17:17:22.608460

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2fd20c0c5358"
down_revision = "5eac8e246390"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "GlobalMessage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("sender_name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("GlobalMessage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_GlobalMessage_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "PersonalMessage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("receiver_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["User.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("PersonalMessage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_PersonalMessage_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("PersonalMessage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_PersonalMessage_timestamp"))

    op.drop_table("PersonalMessage")
    with op.batch_alter_table("GlobalMessage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_GlobalMessage_timestamp"))

    op.drop_table("GlobalMessage")
    # ### end Alembic commands ###
