"""removed 's' and added indices

Revision ID: 327317a6b2af
Revises: 45e5acd494e5
Create Date: 2022-09-10 08:00:09.642782

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "327317a6b2af"
down_revision = "45e5acd494e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("hexagon_index", "Hexagon", ["q", "r"], unique=True)
    op.drop_column("Hexagon", "s")
    op.create_index("tile_index", "Tile", ["q", "r"], unique=True)
    op.drop_column("Tile", "s")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Tile", sa.Column("s", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index("tile_index", table_name="Tile")
    op.add_column("Hexagon", sa.Column("s", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index("hexagon_index", table_name="Hexagon")
    # ### end Alembic commands ###
