"""adding a removed indicator on the Friend object

Revision ID: 38bb8bd661a8
Revises: 70799db92bad
Create Date: 2022-10-17 15:41:20.695276

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "38bb8bd661a8"
down_revision = "70799db92bad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Friend", sa.Column("removed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Friend", "removed")
    # ### end Alembic commands ###
