"""colour to user

Revision ID: 4233dfbb7940
Revises: 19c37ff8148b
Create Date: 2026-01-28 18:53:35.022909

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4233dfbb7940"
down_revision: Union[str, Sequence[str], None] = "19c37ff8148b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column("colour", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "colour")
    # ### end Alembic commands ###
