"""added tile detail on hexagon objects

Revision ID: 45e5acd494e5
Revises: b77dfeefaf33
Create Date: 2022-09-07 09:02:33.733841

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "45e5acd494e5"
down_revision = "b77dfeefaf33"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Hexagon", sa.Column("tiles_detail", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Hexagon", "tiles_detail")
    # ### end Alembic commands ###
