"""adding some extra user information

Revision ID: 48d22f822768
Revises: 08d27bb74869
Create Date: 2022-10-06 17:25:39.415674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "48d22f822768"
down_revision = "08d27bb74869"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("about_me", sa.String(length=140), nullable=True))
    op.add_column("User", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "last_seen")
    op.drop_column("User", "about_me")
    # ### end Alembic commands ###
