"""login

Revision ID: 4e250b2bc401
Revises:
Create Date: 2025-08-21 11:07:38.494720

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e250b2bc401"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("salt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("origin", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_User")),
    )
    op.create_index(op.f("ix_User_username"), "User", ["username"], unique=True)
    op.create_table(
        "UserToken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_expiration", sa.Integer(), nullable=False),
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("refresh_token_expiration", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["User.id"], name=op.f("fk_UserToken_user_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_UserToken")),
    )
    op.create_index(
        op.f("ix_UserToken_access_token"), "UserToken", ["access_token"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_UserToken_access_token"), table_name="UserToken")
    op.drop_table("UserToken")
    op.drop_index(op.f("ix_User_username"), table_name="User")
    op.drop_table("User")
    # ### end Alembic commands ###
