"""profile indicators

Revision ID: 5822e6a8fa59
Revises: a85e9481ad0a
Create Date: 2025-11-17 11:43:36.135428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5822e6a8fa59"
down_revision: Union[str, Sequence[str], None] = "a85e9481ad0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("default_avatar", sa.Boolean(), nullable=False))
    op.add_column("User", sa.Column("profile_version", sa.Integer(), nullable=False))
    op.add_column("User", sa.Column("avatar_version", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "avatar_version")
    op.drop_column("User", "profile_version")
    op.drop_column("User", "default_avatar")
    # ### end Alembic commands ###
