"""adding default avatar indicator on user

Revision ID: 5eac8e246390
Revises: 0fbeba7c3872
Create Date: 2023-04-08 21:20:54.629946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eac8e246390'
down_revision = '0fbeba7c3872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_avatar', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('default_avatar')

    # ### end Alembic commands ###
