"""adding friends

Revision ID: 70799db92bad
Revises: 01ffd9ee8d7c
Create Date: 2022-10-17 15:25:41.935957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70799db92bad'
down_revision = '01ffd9ee8d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('last_time_activity', sa.DateTime(), nullable=True),
    sa.Column('unread_messages', sa.Integer(), nullable=True),
    sa.Column('ignored', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Friend')
    # ### end Alembic commands ###
