"""group and chat stuff

Revision ID: 78ab418c142c
Revises: 97bc978ba8ff
Create Date: 2026-02-06 20:04:39.422517

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78ab418c142c"
down_revision: Union[str, Sequence[str], None] = "97bc978ba8ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Chat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("user_admin_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore[attr-defined]
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore[attr-defined]
        sa.Column("colour", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore[attr-defined]
        sa.Column("default_avatar", sa.Boolean(), nullable=False),
        sa.Column("current_message_id", sa.Integer(), nullable=False),
        sa.Column("last_message_read_id_chat", sa.Integer(), nullable=False),
        sa.Column("message_version", sa.Integer(), nullable=False),
        sa.Column("avatar_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Chat")),
    )
    op.create_table(
        "Group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("unread_messages", sa.Integer(), nullable=False),
        sa.Column("mute", sa.Boolean(), nullable=False),
        sa.Column("mute_timestamp", sa.DateTime(), nullable=True),
        sa.Column("last_message_read_id", sa.Integer(), nullable=False),
        sa.Column("group_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["Chat.id"], name=op.f("fk_Group_group_id_Chat")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["User.id"], name=op.f("fk_Group_user_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Group")),
    )
    op.create_table(
        "Message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("message_type", sa.Integer(), nullable=False),
        sa.Column("replied_to", sa.Integer(), nullable=True),
        sa.Column("receive_remaining", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["Chat.id"], name=op.f("fk_Message_chat_id_Chat")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Message")),
    )
    op.add_column("Friend", sa.Column("chat_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_Friend_chat_id_Chat"), "Friend", "Chat", ["chat_id"], ["id"]
    )
    op.add_column(
        "User",
        sa.Column("colour", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "colour")
    op.drop_constraint(op.f("fk_Friend_chat_id_Chat"), "Friend", type_="foreignkey")
    op.drop_column("Friend", "chat_id")
    op.drop_table("Message")
    op.drop_table("Group")
    op.drop_table("Chat")
    # ### end Alembic commands ###
