"""message, chat and group for communication

Revision ID: 7f8941450783
Revises: 5822e6a8fa59
Create Date: 2025-12-25 09:41:54.185670

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f8941450783"
down_revision: Union[str, Sequence[str], None] = "5822e6a8fa59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Chat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("user_admin_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("group_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column(
            "group_description",
            sqlmodel.sql.sqltypes.AutoString(),  # type: ignore[attr-defined]
            nullable=False,
        ),
        sa.Column("group_colour", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("default_avatar", sa.Boolean(), nullable=False),
        sa.Column("current_message_id", sa.Integer(), nullable=False),
        sa.Column("last_message_read_id_chat", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Chat")),
    )
    op.create_table(
        "Group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("unread_messages", sa.Integer(), nullable=False),
        sa.Column("mute", sa.Boolean(), nullable=False),
        sa.Column("mute_timestamp", sa.DateTime(), nullable=True),
        sa.Column("group_version", sa.Integer(), nullable=False),
        sa.Column("message_version", sa.Integer(), nullable=False),
        sa.Column("avatar_version", sa.Integer(), nullable=False),
        sa.Column("last_message_read_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["Chat.id"], name=op.f("fk_Group_group_id_Chat")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["User.id"], name=op.f("fk_Group_user_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Group")),
    )
    op.create_table(
        "Message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("text_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore[attr-defined]
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("info", sa.Boolean(), nullable=False),
        sa.Column("data", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore[attr-defined]
        sa.Column("data_type", sa.Integer(), nullable=True),
        sa.Column("replied_to", sa.Integer(), nullable=True),
        sa.Column("receive_remaining", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["Chat.id"], name=op.f("fk_Message_group_id_Chat")
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["User.id"], name=op.f("fk_Message_sender_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Message")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Message")
    op.drop_table("Group")
    op.drop_table("Chat")
    # ### end Alembic commands ###
