"""forgot the last changed datetime

Revision ID: 895581a97288
Revises: a6f5e88d0681
Create Date: 2023-01-07 10:44:46.113656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "895581a97288"
down_revision = "a6f5e88d0681"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Tile", sa.Column("last_changed_time", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Tile", "last_changed_time")
    # ### end Alembic commands ###
