"""adding tile lock option

Revision ID: cf16e11a7eb8
Revises: 895581a97288
Create Date: 2023-01-09 18:15:29.265314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf16e11a7eb8"
down_revision = "895581a97288"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("tile_lock", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "tile_lock")
    # ### end Alembic commands ###
