"""default indicator user avatar

Revision ID: f0bdf3309fe4
Revises: a85e9481ad0a
Create Date: 2025-11-12 22:39:18.253485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0bdf3309fe4'
down_revision: Union[str, Sequence[str], None] = 'a85e9481ad0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('default_avatar', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'default_avatar')
    # ### end Alembic commands ###
