"""added posts for user interaction

Revision ID: 08d27bb74869
Revises: 2cd6a6ea940f
Create Date: 2022-10-05 19:07:58.279548

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "08d27bb74869"
down_revision = "2cd6a6ea940f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Post_timestamp"), "Post", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Post_timestamp"), table_name="Post")
    op.drop_table("Post")
    # ### end Alembic commands ###
