"""initial user model

Revision ID: 46bb807f5616
Revises:
Create Date: 2022-05-29 15:49:36.101105

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46bb807f5616"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_User_username"), "User", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_User_username"), table_name="User")
    op.drop_table("User")
    # ### end Alembic commands ###
