"""adding foreign key references

Revision ID: aeef7488a61c
Revises: 17471168a89a
Create Date: 2022-05-29 17:32:56.903612

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aeef7488a61c"
down_revision = "17471168a89a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Tile", sa.Column("hexagon_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "Tile", "Hexagon", ["hexagon_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Tile", type_="foreignkey")
    op.drop_column("Tile", "hexagon_id")
    # ### end Alembic commands ###
