"""fixing some of the friending models

Revision ID: e1636aa46dff
Revises: 2fd20c0c5358
Create Date: 2023-04-27 21:06:28.264812

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1636aa46dff"
down_revision = "2fd20c0c5358"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Friend", schema=None) as batch_op:
        batch_op.add_column(sa.Column("accepted", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Friend", schema=None) as batch_op:
        batch_op.drop_column("accepted")

    # ### end Alembic commands ###
