FROM python:3.14.1-slim

WORKDIR /

RUN apt-get update && \
    apt-get install -y --no-install-recommends git gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir uv

ENV PYTHONPATH=${PYTHONPATH}:/src

COPY age_of_gold_cron/pyproject.toml /pyproject.toml
COPY age_of_gold_cron/README.md /README.md

RUN uv pip install --system --no-cache-dir -e .

COPY age_of_gold_cron/main_cron.py main_cron.py
COPY age_of_gold_cron/age_of_gold_cron /age_of_gold_cron/age_of_gold_cron

RUN mkdir -p /src/static/uploads
